/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPayoutsRouteImport } from './routes/_authenticated/payouts'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminMpesaRouteImport } from './routes/_authenticated/admin.mpesa'
import { Route as AuthenticatedAdmitIndexRouteImport } from './routes/_authenticated/admit.index'
import { Route as AuthenticatedAdmitEventIdRouteImport } from './routes/_authenticated/admit.$eventId'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events.new'
import { Route as AuthenticatedManageEventIdRouteImport } from './routes/_authenticated/manage.$eventId'
import { Route as ApiPublicCoversSplatRouteImport } from './routes/api/public/covers.$'
import { Route as ApiPublicMpesaB2cResultRouteImport } from './routes/api/public/mpesa/b2c-result'
import { Route as ApiPublicMpesaB2cTimeoutRouteImport } from './routes/api/public/mpesa/b2c-timeout'
import { Route as ApiPublicMpesaStkCallbackRouteImport } from './routes/api/public/mpesa/stk-callback'
import { Route as ApiPublicV1EventsRouteImport } from './routes/api/public/v1/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayoutsRoute = AuthenticatedPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/admin/events',
    path: '/admin/events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMpesaRoute = AuthenticatedAdminMpesaRouteImport.update({
  id: '/admin/mpesa',
  path: '/admin/mpesa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdmitIndexRoute = AuthenticatedAdmitIndexRouteImport.update({
  id: '/admit/',
  path: '/admit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdmitEventIdRoute =
  AuthenticatedAdmitEventIdRouteImport.update({
    id: '/admit/$eventId',
    path: '/admit/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageEventIdRoute =
  AuthenticatedManageEventIdRouteImport.update({
    id: '/manage/$eventId',
    path: '/manage/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCoversSplatRoute = ApiPublicCoversSplatRouteImport.update({
  id: '/api/public/covers/$',
  path: '/api/public/covers/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaB2cResultRoute = ApiPublicMpesaB2cResultRouteImport.update({
  id: '/api/public/mpesa/b2c-result',
  path: '/api/public/mpesa/b2c-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaB2cTimeoutRoute =
  ApiPublicMpesaB2cTimeoutRouteImport.update({
    id: '/api/public/mpesa/b2c-timeout',
    path: '/api/public/mpesa/b2c-timeout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpesaStkCallbackRoute =
  ApiPublicMpesaStkCallbackRouteImport.update({
    id: '/api/public/mpesa/stk-callback',
    path: '/api/public/mpesa/stk-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1EventsRoute = ApiPublicV1EventsRouteImport.update({
  id: '/api/public/v1/events',
  path: '/api/public/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/': typeof EventsIndexRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/mpesa': typeof AuthenticatedAdminMpesaRoute
  '/admit/$eventId': typeof AuthenticatedAdmitEventIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/manage/$eventId': typeof AuthenticatedManageEventIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admit/': typeof AuthenticatedAdmitIndexRoute
  '/api/public/covers/$': typeof ApiPublicCoversSplatRoute
  '/api/public/mpesa/b2c-result': typeof ApiPublicMpesaB2cResultRoute
  '/api/public/mpesa/b2c-timeout': typeof ApiPublicMpesaB2cTimeoutRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events': typeof EventsIndexRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/mpesa': typeof AuthenticatedAdminMpesaRoute
  '/admit/$eventId': typeof AuthenticatedAdmitEventIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/manage/$eventId': typeof AuthenticatedManageEventIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admit': typeof AuthenticatedAdmitIndexRoute
  '/api/public/covers/$': typeof ApiPublicCoversSplatRoute
  '/api/public/mpesa/b2c-result': typeof ApiPublicMpesaB2cResultRoute
  '/api/public/mpesa/b2c-timeout': typeof ApiPublicMpesaB2cTimeoutRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/payouts': typeof AuthenticatedPayoutsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/': typeof EventsIndexRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/mpesa': typeof AuthenticatedAdminMpesaRoute
  '/_authenticated/admit/$eventId': typeof AuthenticatedAdmitEventIdRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/manage/$eventId': typeof AuthenticatedManageEventIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admit/': typeof AuthenticatedAdmitIndexRoute
  '/api/public/covers/$': typeof ApiPublicCoversSplatRoute
  '/api/public/mpesa/b2c-result': typeof ApiPublicMpesaB2cResultRoute
  '/api/public/mpesa/b2c-timeout': typeof ApiPublicMpesaB2cTimeoutRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/payouts'
    | '/tickets'
    | '/events/$eventId'
    | '/events/'
    | '/admin/events'
    | '/admin/mpesa'
    | '/admit/$eventId'
    | '/events/new'
    | '/manage/$eventId'
    | '/admin/'
    | '/admit/'
    | '/api/public/covers/$'
    | '/api/public/mpesa/b2c-result'
    | '/api/public/mpesa/b2c-timeout'
    | '/api/public/mpesa/stk-callback'
    | '/api/public/v1/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/payouts'
    | '/tickets'
    | '/events/$eventId'
    | '/events'
    | '/admin/events'
    | '/admin/mpesa'
    | '/admit/$eventId'
    | '/events/new'
    | '/manage/$eventId'
    | '/admin'
    | '/admit'
    | '/api/public/covers/$'
    | '/api/public/mpesa/b2c-result'
    | '/api/public/mpesa/b2c-timeout'
    | '/api/public/mpesa/stk-callback'
    | '/api/public/v1/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/payouts'
    | '/_authenticated/tickets'
    | '/events/$eventId'
    | '/events/'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/mpesa'
    | '/_authenticated/admit/$eventId'
    | '/_authenticated/events/new'
    | '/_authenticated/manage/$eventId'
    | '/_authenticated/admin/'
    | '/_authenticated/admit/'
    | '/api/public/covers/$'
    | '/api/public/mpesa/b2c-result'
    | '/api/public/mpesa/b2c-timeout'
    | '/api/public/mpesa/stk-callback'
    | '/api/public/v1/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiPublicCoversSplatRoute: typeof ApiPublicCoversSplatRoute
  ApiPublicMpesaB2cResultRoute: typeof ApiPublicMpesaB2cResultRoute
  ApiPublicMpesaB2cTimeoutRoute: typeof ApiPublicMpesaB2cTimeoutRoute
  ApiPublicMpesaStkCallbackRoute: typeof ApiPublicMpesaStkCallbackRoute
  ApiPublicV1EventsRoute: typeof ApiPublicV1EventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts': {
      id: '/_authenticated/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AuthenticatedPayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mpesa': {
      id: '/_authenticated/admin/mpesa'
      path: '/admin/mpesa'
      fullPath: '/admin/mpesa'
      preLoaderRoute: typeof AuthenticatedAdminMpesaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admit/': {
      id: '/_authenticated/admit/'
      path: '/admit'
      fullPath: '/admit/'
      preLoaderRoute: typeof AuthenticatedAdmitIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admit/$eventId': {
      id: '/_authenticated/admit/$eventId'
      path: '/admit/$eventId'
      fullPath: '/admit/$eventId'
      preLoaderRoute: typeof AuthenticatedAdmitEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage/$eventId': {
      id: '/_authenticated/manage/$eventId'
      path: '/manage/$eventId'
      fullPath: '/manage/$eventId'
      preLoaderRoute: typeof AuthenticatedManageEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/covers/$': {
      id: '/api/public/covers/$'
      path: '/api/public/covers/$'
      fullPath: '/api/public/covers/$'
      preLoaderRoute: typeof ApiPublicCoversSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/b2c-result': {
      id: '/api/public/mpesa/b2c-result'
      path: '/api/public/mpesa/b2c-result'
      fullPath: '/api/public/mpesa/b2c-result'
      preLoaderRoute: typeof ApiPublicMpesaB2cResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/b2c-timeout': {
      id: '/api/public/mpesa/b2c-timeout'
      path: '/api/public/mpesa/b2c-timeout'
      fullPath: '/api/public/mpesa/b2c-timeout'
      preLoaderRoute: typeof ApiPublicMpesaB2cTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/stk-callback': {
      id: '/api/public/mpesa/stk-callback'
      path: '/api/public/mpesa/stk-callback'
      fullPath: '/api/public/mpesa/stk-callback'
      preLoaderRoute: typeof ApiPublicMpesaStkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/events': {
      id: '/api/public/v1/events'
      path: '/api/public/v1/events'
      fullPath: '/api/public/v1/events'
      preLoaderRoute: typeof ApiPublicV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPayoutsRoute: typeof AuthenticatedPayoutsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminMpesaRoute: typeof AuthenticatedAdminMpesaRoute
  AuthenticatedAdmitEventIdRoute: typeof AuthenticatedAdmitEventIdRoute
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedManageEventIdRoute: typeof AuthenticatedManageEventIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdmitIndexRoute: typeof AuthenticatedAdmitIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPayoutsRoute: AuthenticatedPayoutsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminMpesaRoute: AuthenticatedAdminMpesaRoute,
  AuthenticatedAdmitEventIdRoute: AuthenticatedAdmitEventIdRoute,
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedManageEventIdRoute: AuthenticatedManageEventIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdmitIndexRoute: AuthenticatedAdmitIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiPublicCoversSplatRoute: ApiPublicCoversSplatRoute,
  ApiPublicMpesaB2cResultRoute: ApiPublicMpesaB2cResultRoute,
  ApiPublicMpesaB2cTimeoutRoute: ApiPublicMpesaB2cTimeoutRoute,
  ApiPublicMpesaStkCallbackRoute: ApiPublicMpesaStkCallbackRoute,
  ApiPublicV1EventsRoute: ApiPublicV1EventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
