/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events.new'
import { Route as AuthenticatedManageEventIdRouteImport } from './routes/_authenticated/manage.$eventId'
import { Route as ApiPublicMpesaB2cResultRouteImport } from './routes/api/public/mpesa/b2c-result'
import { Route as ApiPublicMpesaB2cTimeoutRouteImport } from './routes/api/public/mpesa/b2c-timeout'
import { Route as ApiPublicMpesaStkCallbackRouteImport } from './routes/api/public/mpesa/stk-callback'
import { Route as ApiPublicV1EventsRouteImport } from './routes/api/public/v1/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageEventIdRoute =
  AuthenticatedManageEventIdRouteImport.update({
    id: '/manage/$eventId',
    path: '/manage/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMpesaB2cResultRoute = ApiPublicMpesaB2cResultRouteImport.update({
  id: '/api/public/mpesa/b2c-result',
  path: '/api/public/mpesa/b2c-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaB2cTimeoutRoute =
  ApiPublicMpesaB2cTimeoutRouteImport.update({
    id: '/api/public/mpesa/b2c-timeout',
    path: '/api/public/mpesa/b2c-timeout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpesaStkCallbackRoute =
  ApiPublicMpesaStkCallbackRouteImport.update({
    id: '/api/public/mpesa/stk-callback',
    path: '/api/public/mpesa/stk-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1EventsRoute = ApiPublicV1EventsRouteImport.update({
  id: '/api/public/v1/events',
  path: '/api/public/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/manage/$eventId': typeof AuthenticatedManageEventIdRoute
  '/api/public/mpesa/b2c-result': typeof ApiPublicMpesaB2cResultRoute
  '/api/public/mpesa/b2c-timeout': typeof ApiPublicMpesaB2cTimeoutRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/manage/$eventId': typeof AuthenticatedManageEventIdRoute
  '/api/public/mpesa/b2c-result': typeof ApiPublicMpesaB2cResultRoute
  '/api/public/mpesa/b2c-timeout': typeof ApiPublicMpesaB2cTimeoutRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/manage/$eventId': typeof AuthenticatedManageEventIdRoute
  '/api/public/mpesa/b2c-result': typeof ApiPublicMpesaB2cResultRoute
  '/api/public/mpesa/b2c-timeout': typeof ApiPublicMpesaB2cTimeoutRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
  '/api/public/v1/events': typeof ApiPublicV1EventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/tickets'
    | '/events/$eventId'
    | '/events/new'
    | '/manage/$eventId'
    | '/api/public/mpesa/b2c-result'
    | '/api/public/mpesa/b2c-timeout'
    | '/api/public/mpesa/stk-callback'
    | '/api/public/v1/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/tickets'
    | '/events/$eventId'
    | '/events/new'
    | '/manage/$eventId'
    | '/api/public/mpesa/b2c-result'
    | '/api/public/mpesa/b2c-timeout'
    | '/api/public/mpesa/stk-callback'
    | '/api/public/v1/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/tickets'
    | '/events/$eventId'
    | '/_authenticated/events/new'
    | '/_authenticated/manage/$eventId'
    | '/api/public/mpesa/b2c-result'
    | '/api/public/mpesa/b2c-timeout'
    | '/api/public/mpesa/stk-callback'
    | '/api/public/v1/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  ApiPublicMpesaB2cResultRoute: typeof ApiPublicMpesaB2cResultRoute
  ApiPublicMpesaB2cTimeoutRoute: typeof ApiPublicMpesaB2cTimeoutRoute
  ApiPublicMpesaStkCallbackRoute: typeof ApiPublicMpesaStkCallbackRoute
  ApiPublicV1EventsRoute: typeof ApiPublicV1EventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage/$eventId': {
      id: '/_authenticated/manage/$eventId'
      path: '/manage/$eventId'
      fullPath: '/manage/$eventId'
      preLoaderRoute: typeof AuthenticatedManageEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mpesa/b2c-result': {
      id: '/api/public/mpesa/b2c-result'
      path: '/api/public/mpesa/b2c-result'
      fullPath: '/api/public/mpesa/b2c-result'
      preLoaderRoute: typeof ApiPublicMpesaB2cResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/b2c-timeout': {
      id: '/api/public/mpesa/b2c-timeout'
      path: '/api/public/mpesa/b2c-timeout'
      fullPath: '/api/public/mpesa/b2c-timeout'
      preLoaderRoute: typeof ApiPublicMpesaB2cTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/stk-callback': {
      id: '/api/public/mpesa/stk-callback'
      path: '/api/public/mpesa/stk-callback'
      fullPath: '/api/public/mpesa/stk-callback'
      preLoaderRoute: typeof ApiPublicMpesaStkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/events': {
      id: '/api/public/v1/events'
      path: '/api/public/v1/events'
      fullPath: '/api/public/v1/events'
      preLoaderRoute: typeof ApiPublicV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedManageEventIdRoute: typeof AuthenticatedManageEventIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedManageEventIdRoute: AuthenticatedManageEventIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  ApiPublicMpesaB2cResultRoute: ApiPublicMpesaB2cResultRoute,
  ApiPublicMpesaB2cTimeoutRoute: ApiPublicMpesaB2cTimeoutRoute,
  ApiPublicMpesaStkCallbackRoute: ApiPublicMpesaStkCallbackRoute,
  ApiPublicV1EventsRoute: ApiPublicV1EventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
